export const portalPermissions = {
  adminFull: 'admin.full',
  auditView: 'audit.view',
  employeesManage: 'employees.manage',
  onboardingManage: 'onboarding.manage',
  trainingManage: 'training.manage',
  sopManage: 'sop.manage',
  timekeepingManage: 'timekeeping.manage',
  schedulesManage: 'schedules.manage',
  leaveApprove: 'leave.approve',
  payrollManage: 'payroll.manage',
  formulasManage: 'formulas.manage',
  benefitsManage: 'benefits.manage',
  equipmentManage: 'equipment.manage',
  inventoryManage: 'inventory.manage',
  disciplineManage: 'discipline.manage',
  canteenManage: 'canteen.manage',
  reviewsManage: 'reviews.manage',
  rolesManage: 'roles.manage',
} as const;

export type PortalPermission = (typeof portalPermissions)[keyof typeof portalPermissions];

export const rolePermissionMap: Record<string, PortalPermission[]> = {
  ADMIN: [portalPermissions.adminFull, portalPermissions.auditView],
  role_admin: [portalPermissions.adminFull, portalPermissions.auditView],
  'HR Manager': [
    portalPermissions.employeesManage,
    portalPermissions.onboardingManage,
    portalPermissions.trainingManage,
    portalPermissions.sopManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
    portalPermissions.rolesManage,
  ],
  HR_MANAGER: [
    portalPermissions.employeesManage,
    portalPermissions.onboardingManage,
    portalPermissions.trainingManage,
    portalPermissions.sopManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
    portalPermissions.rolesManage,
  ],
  role_hr_manager: [
    portalPermissions.employeesManage,
    portalPermissions.onboardingManage,
    portalPermissions.trainingManage,
    portalPermissions.sopManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
    portalPermissions.rolesManage,
  ],
  'Branch Manager': [
    portalPermissions.schedulesManage,
    portalPermissions.leaveApprove,
    portalPermissions.payrollManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
  ],
  BRANCH_MANAGER: [
    portalPermissions.schedulesManage,
    portalPermissions.leaveApprove,
    portalPermissions.payrollManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
  ],
  role_branch_manager: [
    portalPermissions.schedulesManage,
    portalPermissions.leaveApprove,
    portalPermissions.payrollManage,
    portalPermissions.reviewsManage,
    portalPermissions.auditView,
  ],
  SUPERVISOR: [portalPermissions.schedulesManage, portalPermissions.leaveApprove, portalPermissions.timekeepingManage],
  role_supervisor: [portalPermissions.schedulesManage, portalPermissions.leaveApprove, portalPermissions.timekeepingManage],
  SERVICE_ADVISOR: [portalPermissions.trainingManage, portalPermissions.sopManage],
  role_service_advisor: [portalPermissions.trainingManage, portalPermissions.sopManage],
  CHIEF_MECHANIC: [portalPermissions.equipmentManage, portalPermissions.inventoryManage, portalPermissions.trainingManage],
  role_chief_mechanic: [portalPermissions.equipmentManage, portalPermissions.inventoryManage, portalPermissions.trainingManage],
  SENIOR_MECHANIC: [portalPermissions.equipmentManage, portalPermissions.trainingManage],
  role_senior_mechanic: [portalPermissions.equipmentManage, portalPermissions.trainingManage],
  GENERAL_MECHANIC: [portalPermissions.trainingManage],
  role_general_mechanic: [portalPermissions.trainingManage],
  OJT: [portalPermissions.trainingManage],
  role_ojt: [portalPermissions.trainingManage],
  CASHIER: [portalPermissions.payrollManage, portalPermissions.canteenManage],
  role_cashier: [portalPermissions.payrollManage, portalPermissions.canteenManage],
  CANTEEN_STAFF: [portalPermissions.canteenManage],
  role_canteen_staff: [portalPermissions.canteenManage],
  INVENTORY_STAFF: [portalPermissions.inventoryManage, portalPermissions.equipmentManage],
  role_inventory_staff: [portalPermissions.inventoryManage, portalPermissions.equipmentManage],
};
